---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age13jr30sye28m9sqgczpegxad283jsqjhh6ytyrmrq86p9d0fjx3asjnesq3
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age13jr30sye28m9sqgczpegxad283jsqjhh6ytyrmrq86p9d0fjx3asjnesq3
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age13jr30sye28m9sqgczpegxad283jsqjhh6ytyrmrq86p9d0fjx3asjnesq3
