apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:7Gfa2p6ZMO5uWwH/ggoXh7OrfXU=,iv:+YvpKB+Y0u4ZZy999jTFzkbjlbzG/cFLGMlprTPg9F4=,tag:2BV/38Lro2v+32urgfMM6w==,type:str]
    api-key: ENC[AES256_GCM,data:IFKGqB7ON2V1BW3VCE3qFh/y/Wi8R7FAPRRO0DI4sgDb26Qmjg==,iv:MAY5VTzJZXgyQRI46bsXHQ6nExNmG6ZQXx8Td3Sm2qQ=,tag:nBdYYD1llp2n24m1qSvFqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13jr30sye28m9sqgczpegxad283jsqjhh6ytyrmrq86p9d0fjx3asjnesq3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VnNBb1RGdmx2Q2crSnVY
            N2g5elJkOEZaSUVXVnpEWEJIQURYbFB5Y1JjCjU3WWNXZWhXNy9Ienh4K3Ava0pq
            ZEJFa1IyOXQwMDJRdzk0enpTTTdSZVEKLS0tIGZUUlBmSTVtbTR5NVdoYnpzMnhs
            ODl0djRtdDBScGovNm5wNnk2RGZlNFkKk7bQNRV4OfR0G8SeYNpyGG3FBHEC6mq4
            mFI8/flRA52ApZC2uWKxmLBteCaiQqSnKGhU+4GqhqoOOP5JWuLYXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-13T08:54:49Z"
    mac: ENC[AES256_GCM,data:VQBwa48PciKM9GX76O0bUlIkjl4LqkA6rUjt9tQTsIbkGzhAXa0thSaqH/QSKo0JVYahtgmSMwutt7uQp1XxnR6pTFd+gaS+7Tqs8K9BrUm5y1J1RqBhBADVcxw+C4rcbgVxIFfhM5rZ5+rvOuYGZDbWPvSPHPLozDt7OjuSV/8=,iv:VKg83NOg16CSz4ukwm5TXhfT1uvo6yem3xuJ76o0kMI=,tag:S4l8dLPyQUKHdqsxioJm3w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
