---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./echo-server/ks.yaml
  - ./hajimari/ks.yaml
  - ./whoogle/ks.yaml
  - ./plex/ks.yaml
#  - ./whoogle/ks.yaml
  - ./overseerr/ks.yaml
